### ISSUE TITLE
Laravel 5.3 - UrlWindowPresenterTrait UrlWindowPresenterTrait

### ISSUE THREAD

**Issue by summerblue** [Landish/Pagination#12]
```
FatalErrorException in Pagination.php line 10:
Trait 'Illuminate\Pagination\UrlWindowPresenterTrait' not found
```

**Comment by tsunamilx** [comment]
+1

**Comment by insight-media** [comment]
I'm still having this issue with Laravel 5.4

FatalErrorException in Pagination.php line 10:
Trait 'Illuminate\Pagination\UrlWindowPresenterTrait' not found

**Comment by Landish** [comment]
Documentation needs to be updated. 
It only works for < 5.2 versions.

After 5.3 pagination template files were separated and you can customize them in blade files.
Run the command: 
```
php artisan vendor:publish --tag=laravel-pagination
```

and and edit `resources/views/vendor/pagination/default.blade.php` file.

**Comment by insight-media** [comment]
Thank you for the info !
