### ISSUE TITLE
Pretty URLs

### ISSUE THREAD

**Issue by pdefreitas** [Landish/Pagination#7]
It would be very cool if this package supports pretty urls just like some similar packages.

**Comment by Landish** [comment]
@pdefreitas, Can you tell me, which packages support pretty urls?

**Comment by pdefreitas** [comment]
https://github.com/DeSmart/pagination

**Comment by Landish** [comment]
Thank you @pdefreitas ,

My package originally was created to make html output easy. It was never intended to change url structure or something like that.

I'm not thinking about adding this functionality at this time, but in future, i't might be changed.
