### ISSUE TITLE
Pagination with per page field

### ISSUE THREAD

**Issue by Harrrrry** [Landish/Pagination#8]
Hyy @Landish,

How can i add per page selection filed like 15,30,60,120 with pagination
and how can i append link dynamically 
like my url www.example.com?x=2
and i want to append page=2
like www.example.com?x=2&page=2

Is this possible ?

**Comment by Landish** [comment]
Hello, @Harrrrry 

Thanks for using this package.

To append extra params to your links you can call `appends()` method before `render()`:

```php
{!! $items->appends(['key' => 'value'])->render(new App\Pagination($items))  !!}
```

It's written in documentation section: [Appending To Pagination Links](https://github.com/Landish/Pagination#appending-to-pagination-links).

**Comment by Harrrrry** [comment]
Thanks ok, and can you suggest me for per page selection data

**Comment by Landish** [comment]
The `paginate()` method accepts optional parameter.

Something like this:

```php
public function index(Request $request) {
    $posts = Post::paginate($request->get('per_page', 15));
    return view('posts', compact('posts'));
}
```

In this case, if you pass additional value as `per_page` to your query string, the number of specific items will be displayed. 

And if i'm correct, as a second argument of the `$request->get()` method, you can pass the default number of items, if `per_page` hasn't been set.

**Comment by Harrrrry** [comment]
Thanks @Landish its working man :)
