### ISSUE TITLE
Available Pages Materialize UI Click Issue

### ISSUE THREAD

**Issue by zanechua** [Landish/Pagination#9]
I know the proper way of the click for Materialize for the $availablePageWrapper is

`$availablePageWrapper = <li class="waves-effect"><a href="%s">%s</a></li>`

but I think it should be

`$availablePageWrapper = '<a href="%s"><li class="waves-effect">%s</li></a>'`

With the first implementation when you click on any area that isn't the number, the wave effect is triggered but the link won't proceed forward. Only when you specifically place your mouse over the number then you will be able to click the link. In my opinion this is flawed. It makes the user think that they have clicked the link but in actual fact, nothing has happened.

The modification actually works as expected and doesn't seem to have any unintended UI issues with Materialize.

**Comment by Landish** [comment]
@zanechua 

Putting `li` tag in `a` isn't correct. 

[Materialize was submitted](https://github.com/Landish/Pagination/pull/1) by @arandilopez and it corresponds to the given documentation: http://materializecss.com/pagination.html.

So, at this moment I don't think that there is some issue about that.

If you're having some troubles with the given code, feel free to change any params, as you like.

**Comment by zanechua** [comment]
@Landish 

Yup. I do know it's incorrect. But I'm talking in more of terms of usability and what the user would do as mentioned in the first post. Cheers.
